# Site settings
title: aberCompSoc
description: >
 Site for the Aberystwyth Computer Science Society

baseurl: ""
url: "http://abercompsoc.github.io"

author:
 fullname: aberCompSoc
 #googleplus: https://www.google.com/+
 github: abercompsoc
 twitter: abercompsoc

collections:	
 authors:		

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
